[theme]
primaryColor = "#00FFFF"          # Cyan
backgroundColor = "#0D1B2A"       # Dark navy blue
secondaryBackgroundColor = "#1B263B" 
textColor = "#E0E1DD"             # Light gray
font = "sans serif"